# パッケージ管理
[[plugins]]
repo = 'Shougo/dein.vim'

# Unite I/F
[[plugins]]
repo = 'Shougo/unite.vim'

# Unite - ソースコードのアウトライン
[[plugins]]
repo = 'Shougo/unite-outline'

# Unite - Rails関連ディレクトリをuniteで操作
[[plugins]]
repo = 'basyura/unite-rails'
on_ft = ['ruby']

# snippets
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'

# 非同期実行
[[plugins]]
repo = 'thinca/vim-quickrun'

# 非同期実行
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# Vimプラグイン用
[[plugins]]
repo = 'vim-jp/vital.vim'

# quickfixの内容をステータスバーに表示
[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

# エラー位置にカーソルが来たときにステータスバーに表示
[[plugins]]
repo = 'dannyob/quickfixstatus'

# visual-mode選択拡張
[[plugins]]
repo = 'terryma/vim-expand-region'

# パワーライン
[[plugins]]
repo = 'itchyny/lightline.vim'

# VimからGit操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# シンタックスエラーの場合に行番号へサイン表示
[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

# wakatimeでの操作ログ取得
[[plugins]]
repo = 'wakatime/vim-wakatime'

# snippet plugin
[[plugins]]
repo = 'Shougo/neosnippet.vim'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# snippets
[[plugins]]
repo = 'honza/vim-snippets'

# 閉じカッコをインテリセンスに
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# :Aと:Rで該当するRailsファイルに移動する
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# テキストオブジェクト拡張
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

# typescriptのsyntax-highlight
[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = ['typescript']

# Vimからブラウザオープン
[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo  = 'rcmdnk/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo  = 'pocke/dicts'
on_ft = ['ruby']

[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo  = 'thoughtbot/vim-rspec'
on_ft = ['ruby']

[[plugins]]
repo  = 'todesking/ruby_hl_lvar.vim'
on_ft = ['ruby']

[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['haml', 'ruby', 'eruby']

[[plugins]]
repo  = 'alpaca-tc/vim-endwise.git'
on_i  = 1
on_ft = ['ruby']

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# ファイルタイプごとにコメントアウト切り替え
[[plugins]]
repo = 'tyru/caw.vim'

# 行DIFFツール
[[plugins]]
repo = 'AndrewRadev/linediff.vim'

# Yank&Register拡張
[[plugins]]
repo = 'Shougo/neoyank.vim'

# GoでVim
[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

# 非同期Linter
[[plugins]]
repo = 'w0rp/ale'

# vimhelp-ja
[[plugins]]
repo = 'vim-jp/vimdoc-ja'

# slim syntax
[[plugins]]
repo = 'slim-template/vim-slim'
on_ft = ['slim']

# switch and circle
[[plugins]]
repo = 'uplus/vim-clurin'

# display sepalate dispatcher
[[plugins]]
repo = 'tpope/vim-dispatch'

# test-plugin
[[plugins]]
repo = 'janko-m/vim-test'
depends = ['vim-dispatch']
hook_add = '''
let g:test#strategy = 'dispatch'
'''

# リファレンス
[[plugins]]
repo  = 'thinca/vim-ref'

# vimからtigを使う
[[plugins]]
repo  = 'iberianpig/tig-explorer.vim'

# vimからrangerを使う
[[plugins]]
repo  = 'iberianpig/ranger-explorer.vim'

# 自動保存
[[plugins]]
repo  = 'vim-scripts/vim-auto-save'

# 英英辞書
[[plugins]]
repo  = 'mmisono/ref-dicts-en'

# solidity
[[plugins]]
repo  = 'tomlion/vim-solidity'
