# パッケージ管理
[[plugins]]
repo = 'Shougo/dein.vim'

# Unite I/F
[[plugins]]
repo = 'Shougo/unite.vim'

# Unite - ソースコードのアウトライン
[[plugins]]
repo = 'Shougo/unite-outline'

# Unite - Rails関連ディレクトリをuniteで操作
[[plugins]]
repo = 'basyura/unite-rails'
on_ft = ['ruby']

# snippets
[[plugins]]
repo = 'Shougo/neocomplete.vim'
if = 'has("lua")'
on_i = 1

[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

# 非同期実行
[[plugins]]
repo = 'osyo-manga/vim-watchdogs'

# 非同期実行
[[plugins]]
repo = 'thinca/vim-quickrun'

# 非同期実行
[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

# quickfixの内容をステータスバーに表示
[[plugins]]
repo = 'KazuakiM/vim-qfstatusline'

# エラー位置にカーソルが来たときにステータスバーに表示
[[plugins]]
repo = 'dannyob/quickfixstatus'

[[plugins]]
repo = 'terryma/vim-expand-region'

# パワーライン
[[plugins]]
repo = 'itchyny/lightline.vim'

# VimからGit操作
[[plugins]]
repo = 'tpope/vim-fugitive'

# シンタックスエラーの場合に行番号へサイン表示
[[plugins]]
repo = 'KazuakiM/vim-qfsigns'

# wakatimeでの操作ログ取得
[[plugins]]
repo = 'wakatime/vim-wakatime'

# snippet plugin
[[plugins]]
repo = 'Shougo/neosnippet.vim'

# snippets
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# snippets
[[plugins]]
repo = 'honza/vim-snippets'

# 閉じカッコをインテリセンスに
[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1

# :Aと:Rで該当するRailsファイルに移動する
[[plugins]]
repo = 'tpope/vim-rails'
on_ft = ['ruby']

# テキストオブジェクト拡張
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'hail2u/vim-css3-syntax'
on_ft = ['css', 'scss']

[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']

[[plugins]]
repo = 'tyru/open-browser.vim'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo  = 'rcmdnk/vim-markdown'
on_ft = ['markdown']

[[plugins]]
repo  = 'vim-ruby/vim-ruby'
on_ft = ['ruby']

[[plugins]]
repo  = 'pocke/dicts'
on_ft = ['ruby']

[[plugins]]
repo  = 'pocke/dicts'
on_ft = ['ruby']
lazy = 1

[[plugins]]
repo  = 'tpope/vim-bundler'
on_ft = ['ruby']

[[plugins]]
repo  = 'thoughtbot/vim-rspec'
on_ft = ['ruby']

[[plugins]]
repo  = 'todesking/ruby_hl_lvar.vim'
on_ft = ['ruby']

[[plugins]]
repo  = 'tpope/vim-rails'
on_ft = ['haml', 'ruby', 'eruby']

[[plugins]]
repo  = 'alpaca-tc/vim-endwise.git'
on_i  = 1
on_ft = ['ruby']

# マルチカーソル
[[plugins]]
repo = 'terryma/vim-multiple-cursors'

# インデント可視化
[[plugins]]
repo = 'Yggdroot/indentLine'

# ペースト時のインデントを無効
[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

# ファイルタイプごとにコメントアウト切り替え
[[plugins]]
repo = 'tyru/caw.vim'

# DIFFツール
[[plugins]]
repo = 'AndrewRadev/linediff.vim'
